apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-second-deployment
spec:
  selector:
    matchLabels:
      name: my-app-2
  template:
    metadata:
      labels:
        name: my-app-2
    spec:
      containers:
        - name: mariadb
          image: mariadb:latest
          args:
            - --init-file
            - /shared-files/schema.sql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-credentials
                  key: mysql-root-password
            - name: MYSQL_ROOT_HOST
              value: "%"
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/mysql
            - name: root
              mountPath: /shared-files
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
      volumes:
        - name: db-data
          hostPath:
            path: /data/volume-example
        - name: root
          hostPath:
            path: /
---
apiVersion: v1
kind: Service
metadata:
  name: my-second-service
spec:
  type: ClusterIP
  selector:
    name: my-app-2
  ports:
    - port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-credentials
type: Opaque
data:
  mysql-root-password: cGFzc3dvcmQuMQ==
---

